apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "the-block-node.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "the-block-node.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "the-block-node.name" . }}
    spec:
      containers:
        - name: node
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
          resources: {{- toYaml .Values.resources | nindent 12 }}
