apiVersion: v1
kind: Service
metadata:
  name: {{ include "the-block-node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "the-block-node.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
