[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crypto_suite" }
rand = { path = "../rand" }
thiserror = "1"
httpd = { path = "../httpd" }
serde = { version = "1", features = ["derive"] }
foundation_serialization = { path = "../foundation_serialization" }
hex = "0.4"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
ledger = { path = "../../ledger" }
foundation_lazy = { path = "../foundation_lazy" }
base64_fp = { path = "../base64_fp" }
native-tls = "0.2"
subtle = "2"
metrics = "0.21"

# optional PQ signatures
pqcrypto-dilithium = { version = "0.5", optional = true }

[features]
hid = ["hidapi"]
webusb = []
dilithium = ["pqcrypto-dilithium"]

[dependencies.hidapi]
version = "2"
optional = true

[dev-dependencies]
rcgen = "0.11"
sys = { path = "../sys" }
runtime = { path = "../runtime" }
