[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "1", features = ["std"] }
rand = "0.7"
thiserror = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"

[features]
hid = ["hidapi"]
webusb = []

[dependencies.hidapi]
version = "2"
optional = true

[dev-dependencies]
httpmock = "0.7"
