[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crypto_suite" }
rand = { path = "../rand" }
thiserror = { path = "../thiserror" }
httpd = { path = "../httpd" }
serde = { version = "1", features = ["derive"] }
foundation_serialization = { path = "../foundation_serialization" }
tracing = "0.1"
ledger = { path = "../../ledger" }
foundation_lazy = { path = "../foundation_lazy" }
base64_fp = { path = "../base64_fp" }
foundation_metrics = { path = "../foundation_metrics" }

# optional PQ signatures
pqcrypto-dilithium = { version = "0.5", optional = true }

[features]
hid = ["hidapi"]
webusb = []
dilithium = ["pqcrypto-dilithium"]

[dependencies.hidapi]
version = "2"
optional = true

[dev-dependencies]
foundation_tls = { path = "../foundation_tls" }
foundation_time = { path = "../foundation_time" }
base64_fp = { path = "../base64_fp" }
sys = { path = "../sys" }
runtime = { path = "../runtime" }
testkit = { path = "../testkit" }
