[profile.default]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }
test-threads = 1

[profile.quic]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }
test-threads = 1
