[profile.default]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }

[profile.default.env]
RUST_TEST_THREADS = "1"

[profile.quic]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }
features = ["quic"]
[profile.quic.env]
RUST_TEST_THREADS = "1"
