[profile.default]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }
test-threads = "num-cpus"

[profile.quic]
retries = 0
slow-timeout = { period = "60s", terminate-after = 1 }
test-threads = "num-cpus"

[profile.ci]
retries = 1
slow-timeout = { period = "60s", terminate-after = 1 }
test-threads = "num-cpus"
failure-output = "immediate"
