[package]
name = "log-indexer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
crypto_suite = { path = "../../crates/crypto_suite" }
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.30", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
coding = { path = "../crates/coding" }
