[package]
name = "log-indexer-cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
log_index = { path = "../../crates/log_index" }

[features]
default = []
sqlite-migration = ["log_index/sqlite-migration"]
telemetry = []

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
