[package]
name = "coding"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["std"] }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
