[package]
name = "gov-graph"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
foundation_serialization = { path = "../../crates/foundation_serialization" }
serde = { workspace = true }
the_block = { path = "../../node" }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
