[package]
name = "foundation_async"
version = "0.1.0"
edition = "2021"
authors = ["The Block Developers"]
license = "Apache-2.0"
description = "First-party async primitives and utilities"

[dependencies]
