[package]
name = "foundation_tls"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crypto_suite" }
foundation_time = { path = "../foundation_time" }
thiserror = "1"
rand = { path = "../rand" }
