[package]
name = "foundation_tls"
version = "0.1.0"
edition = "2021"

[dependencies]
base64_fp = { path = "../base64_fp" }
crypto_suite = { path = "../crypto_suite" }
foundation_time = { path = "../foundation_time" }
thiserror = { path = "../thiserror" }
rand = { path = "../rand" }
