[package]
name = "indexer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
foundation_serialization = { path = "../../crates/foundation_serialization" }
foundation_sqlite = { path = "../../crates/foundation_sqlite" }
httpd = { path = "../../crates/httpd" }
http_env = { path = "../../crates/http_env" }
runtime = { path = "../../crates/runtime" }
the_block = { path = "../../node", default-features = false }

[dev-dependencies]
sys = { path = "../../crates/sys" }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
