[package]
name = "tb-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
httpd = { path = "../../crates/httpd" }
serde = { version = "1", features=["derive"] }
foundation_serialization = { path = "../../crates/foundation_serialization" }
wallet = { path = "../../crates/wallet" }
crypto_suite = { path = "../../crates/crypto_suite" }
