[package]
name = "tb-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features=["derive"] }
httpd = { path = "../../crates/httpd" }
serde = { version = "1", features=["derive"] }
serde_json = "1"
hex = "0.4"
wallet = { path = "../../crates/wallet" }
