[package]
name = "bench-harness"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
diagnostics = { path = "../../crates/diagnostics" }
cli_core = { path = "../../crates/cli_core" }
coding = { path = "../../crates/coding" }
foundation_serialization = { path = "../../crates/foundation_serialization" }
rand = { path = "../../crates/rand" }
sys = { path = "../../crates/sys" }


[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
