[package]
name = "governance"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
bincode = "1"
nalgebra = { version = "0.32", features = ["std"] }
rand = "0.8"
rustdct = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = { version = "0.34" }
statrs = "0.16"

[dev-dependencies]
tempfile = "3"
