global:
  scrape_interval: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'the_block'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9898']
  - job_name: 'swarm'
    static_configs:
      - targets:
          - 'localhost:9021'
          - 'localhost:9022'
          - 'localhost:9023'
          - 'localhost:9024'
          - 'localhost:9025'
