[package]
name = "contract-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
hex = "0.4"
the_block = { path = "../node" }
bridges = { path = "../bridges" }
bincode = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dex = { path = "../dex" }
