[package]
name = "contract-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
wallet = { path = "../crates/wallet", optional = true, features = ["dilithium"] }
clap = { version = "4", features = ["derive"] }
hex = "0.4"
the_block = { path = "../node" }
bridges = { path = "../bridges" }
bincode = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dkg = { path = "../dkg", optional = true }
anyhow = "1"
dex = { path = "../dex" }
ed25519-dalek = { version = "2" }
sha3 = "0.10"
ripemd160 = "0.10"
storage = { path = "../storage" }
tokio = { version = "1", features = ["rt", "macros", "net"] }
tokio-tungstenite = "0.20"
futures = "0.3"
light-client = { path = "../crates/light-client" }

[features]
quantum = ["wallet"]
