[package]
name = "foundation_bigint"
version = "0.1.0"
edition = "2021"
authors = ["The Block Developers"]
license = "MIT OR Apache-2.0"
description = "First-party arbitrary-precision unsigned integer implementation"

[dependencies]
