[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["The Block Developers"]
description = "First-party concurrency primitives"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", optional = true }
