[package]
name = "storage_engine"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = []

[dependencies]
base64_fp = { path = "../base64_fp" }
diagnostics = { path = "../diagnostics" }
foundation_serialization = { path = "../foundation_serialization" }
sys = { path = "../sys" }

[build-dependencies]
dependency_guard = { path = "../dependency_guard" }

