[package]
name = "storage_engine"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
thiserror = "1"
parking_lot = "0.12"
tempfile = "3"
base64_fp = { path = "../base64_fp" }
bincode = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

