[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
thiserror = "1"
hex = "0.4"
rocksdb = "0.21"
serde_json = "1"

[dev-dependencies]
tempfile = "3"
