[package]
name = "remote-signer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
foundation_serialization = { path = "../../crates/foundation_serialization" }
wallet = { path = "../../crates/wallet" }
qrcode = "0.12"

[features]
default = []

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
