beta_storage_sub = 0.05
gamma_read_sub = 0.02
kappa_cpu_sub = 0.01
lambda_bytes_out_sub = 0.005
risk_lambda = 2.772588722239781
entropy_phi = 2.0
vdf_kappa = 268435456
haar_eta = 1.5
util_var_threshold = 0.1
fib_window_base_secs = 4.0
heuristic_mu = 0.5
