[package]
name = "sys"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crypto_suite" }

[target.'cfg(windows)'.dependencies]
foundation_windows = { path = "../foundation_windows" }
