[package]
name = "p2p_overlay"
version = "0.1.0"
edition = "2021"


[dependencies]
crypto_suite = { path = "../crypto_suite" }
foundation_serialization = { path = "../foundation_serialization" }

[dev-dependencies]
sys = { path = "../sys" }

