[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
git2 = "0.18"
anyhow = "1"
foundation_serialization = { path = "../../crates/foundation_serialization" }

[[bin]]
name = "refcheck"
path = "../refcheck.rs"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
