[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cli_core = { path = "../../crates/cli_core" }
diagnostics = { path = "../../crates/diagnostics" }
foundation_serialization = { path = "../../crates/foundation_serialization" }
monitoring-build = { path = "../../monitoring" }

[[bin]]
name = "refcheck"
path = "../refcheck.rs"

[dev-dependencies]
sys = { path = "../../crates/sys" }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
