[package]
name = "httpd"
version = "0.1.0"
edition = "2024"

[dependencies]
codec = { path = "../codec" }
runtime = { path = "../runtime" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
thiserror = "1"
tracing = "0.1"
rustls = { version = "0.23", default-features = false, features = ["std", "ring"] }
rustls-pemfile = "2"
