[package]
name = "jurisdiction"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
foundation_serialization = { path = "../foundation_serialization" }
log = "0.4"
base64_fp = { path = "../base64_fp" }
crypto_suite = { path = "../crypto_suite" }
foundation_lazy = { path = "../foundation_lazy" }
httpd = { path = "../httpd" }

# optional post-quantum encryption
pqcrypto-kyber = { version = "0.8", optional = true }

[features]
default = []
pq = ["pqcrypto-kyber"]

[dev-dependencies]
tempfile = "3"
