[package]
name = "jurisdiction"
version = "0.1.0"
edition = "2021"

[dependencies]
foundation_serialization = { path = "../foundation_serialization" }
diagnostics = { path = "../diagnostics" }
base64_fp = { path = "../base64_fp" }
crypto_suite = { path = "../crypto_suite" }
foundation_lazy = { path = "../foundation_lazy" }
httpd = { path = "../httpd" }
http_env = { path = "../http_env" }

# optional post-quantum encryption
pqcrypto-kyber = { path = "../pqcrypto_kyber", optional = true }

[features]
default = []
pq = ["pqcrypto-kyber"]

[dev-dependencies]
sys = { path = "../sys" }
