[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30", features=["bundled"] }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
bincode = "1.3"
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
the_block = { path = "../node" }
blake3 = "1"
storage = { path = "../storage" }
serde_json = "1"
wasmprinter = "0.2"

[dev-dependencies]
tempfile = "3"
wat = "1"
