[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[features]
default = []
inhouse = [
    "dep:crypto_suite",
    "dep:rand",
    "dep:runtime",
    "dep:sys",
    "dep:foundation_serialization",
]
quinn = [
    "dep:crypto_suite",
    "dep:dashmap",
    "dep:quinn",
    "dep:rand",
    "dep:runtime",
    "dep:rustls",
    "dep:foundation_tls",
]
"s2n-quic" = [
    "dep:base64_fp",
    "dep:crypto_suite",
    "dep:rand",
    "dep:runtime",
    "dep:sys",
    "dep:foundation_time",
    "dep:x509-parser",
    "dep:foundation_serialization",
    "dep:foundation_tls",
]
quic = ["quinn", "s2n-quic"]

[dependencies]
diagnostics = { path = "../diagnostics" }
base64_fp = { path = "../base64_fp", optional = true }
dashmap = { version = "5", optional = true }
sys = { path = "../sys", optional = true }
crypto_suite = { path = "../crypto_suite", optional = true }
foundation_lazy = { path = "../foundation_lazy" }
rand = { path = "../rand", optional = true }
runtime = { path = "../runtime", default-features = false, features = ["inhouse-backend"], optional = true }
quinn = { version = "0.10", features = ["rustls"], optional = true }
rustls = { version = "0.21", features = ["dangerous_configuration"], optional = true }
foundation_time = { path = "../foundation_time", optional = true }
x509-parser = { version = "0.16", optional = true }
foundation_serialization = { path = "../foundation_serialization", optional = true }
concurrency = { path = "../concurrency", features = ["serde"] }
foundation_tls = { path = "../foundation_tls", optional = true }

