[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[features]
default = []
inhouse = ["dep:anyhow", "dep:crypto_suite", "dep:rand", "dep:serde", "dep:serde_json", "dep:runtime"]
quinn = [
    "dep:anyhow",
    "dep:crypto_suite",
    "dep:dashmap",
    "dep:quinn",
    "dep:rand",
    "dep:rcgen",
    "dep:runtime",
    "dep:rustls",
]
"s2n-quic" = [
    "dep:anyhow",
    "dep:base64_fp",
    "dep:crypto_suite",
    "dep:sys",
    "dep:hex",
    "dep:rand",
    "dep:rcgen",
    "dep:s2n-quic",
    "dep:serde",
    "dep:serde_json",
    "dep:time",
    "dep:x509-parser",
]
quic = ["quinn", "s2n-quic"]

[dependencies]
anyhow = { version = "1", optional = true }
async-trait = "0.1"
base64_fp = { path = "../base64_fp", optional = true }
dashmap = { version = "5", optional = true }
sys = { path = "../sys", optional = true }
crypto_suite = { path = "../crypto_suite", optional = true }
hex = { version = "0.4", optional = true }
once_cell = "1"
rand = { path = "../rand", optional = true }
rcgen = { version = "0.12", optional = true }
runtime = { path = "../runtime", default-features = false, features = ["inhouse-backend"], optional = true }
quinn = { version = "0.10", features = ["rustls"], optional = true }
rustls = { version = "0.21", features = ["dangerous_configuration"], optional = true }
s2n-quic = { version = "1", features = ["unstable-provider-io-testing"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
time = { version = "0.3", optional = true }
x509-parser = { version = "0.16", optional = true }

[dev-dependencies]
tempfile = "3"
