[package]
name = "wallet-remote-signer-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
wallet = { path = "../../crates/wallet" }
ledger = { path = "../../ledger" }
hex = "0.4"
serde = { version = "1", features=["derive"] }
serde_json = "1"
httpd = { path = "../../crates/httpd" }
runtime = { path = "../../crates/runtime" }
