[package]
name = "dual-key-migrate"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
wallet = { path = "../../crates/wallet", features=["dilithium"] }
crypto = { path = "../../crypto", features=["quantum"] }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
