[package]
name = "dual-key-migrate"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
foundation_serialization = { path = "../../crates/foundation_serialization" }
crypto = { path = "../../crypto", features=["quantum"] }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
