[package]
name = "python_bridge"
version = "0.1.0"
edition = "2021"

[features]
default = []
python-bindings = ["python_bridge_macros"]

[dependencies]
python_bridge_macros = { path = "../python_bridge_macros", optional = true }

