[package]
name = "mobile-light-client-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
light-client = { path = "../../crates/light-client" }
wallet = { path = "../../crates/wallet" }
crypto_suite = { path = "../../crates/crypto_suite" }
serde = { version = "1", features=["derive"] }
foundation_serialization = { path = "../../crates/foundation_serialization" }
the_block = { path = "../../node" }
httpd = { path = "../../crates/httpd" }
runtime = { path = "../../crates/runtime" }

[[bin]]
name = "mesh"
path = "src/bin/mesh.rs"
