[package]
name = "dex"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
foundation_serialization = { path = "../crates/foundation_serialization" }
crypto_suite = { path = "../crates/crypto_suite" }

[dev-dependencies]
testkit = { path = "../crates/testkit" }
