[package]
name = "probe"
version = "0.1.0"
edition = "2021"

[dependencies]
cli_core = { path = "../cli_core" }
httpd = { path = "../httpd" }
foundation_serialization = { path = "../foundation_serialization" }
thiserror = "1"

