[package]
name = "auto-profile"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", default-features = false }
pprof = { version = "0.11", features = ["flamegraph"] }
blake3 = "1"
