[package]
name = "inflation"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crates/crypto_suite" }
rand = { path = "../crates/rand" }
foundation_serialization = { path = "../crates/foundation_serialization" }
serde = { workspace = true }
