[package]
name = "inflation"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_suite = { path = "../crates/crypto_suite" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
