[package]
name = "dependency_registry"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
diagnostics = { path = "../../crates/diagnostics" }
cargo_metadata = "0.18"
cli_core = { path = "../../crates/cli_core" }
camino = "1.1"
concurrency = { path = "../../crates/concurrency" }
foundation_serialization = { path = "../../crates/foundation_serialization" }
foundation_time = { path = "../../crates/foundation_time" }
runtime = { path = "../../crates/runtime", default-features = false, features = ["inhouse-backend"] }

[dev-dependencies]
sys = { path = "../../crates/sys" }


[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
