[package]
name = "release_tests"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dev-dependencies]
sys = { path = "../../crates/sys" }

[build-dependencies]
dependency_guard = { path = "../../crates/dependency_guard" }
